
set undodir=$XDG_CACHE_HOME/vim/undo
set directory=$XDG_CACHE_HOME/vim/swap
set backupdir=$XDG_CACHE_HOME/vim/backup
set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo'
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after


set encoding=utf-8

" display
syntax on
set background=dark
set number
set ruler
set laststatus=2
set showcmd

" edit
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent

" filetype plugin indent on

" file save
set confirm
set hidden
" set noswapfile
set nobackup

" cursor move
set whichwrap=b,s,h,l,<,>,[,]
set backspace=indent,eol,start

" completion

set wildmenu " about file open
set wildmode=longest,full

" search
set ignorecase
set hlsearch
set incsearch
set smartcase


function s:RemoveNetrwhist()
    if filereadable($XDG_CONFIG_HOME."/vim/.netrwhist")
        call delete($XDG_CONFIG_HOME."/vim/.netrwhist")
    endif
endfunction
autocmd VimLeave * call s:RemoveNetrwhist()
