# !Private homebrew tap repository
tap "iwai/tap"
cask "iwai/tap/font-ricty-diminished-nerd-font"


brew "fish"
brew "anyenv"
brew "git-secrets"
brew "hub"
# brew "pandoc"
brew "peco"
brew "tree"
# brew "zlib"

tap "d12frosted/emacs-plus"
brew "d12frosted/emacs-plus/emacs-plus"


cask "google-backup-and-sync"
